server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: http://order-service:8081
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: orderServiceCircuitBreaker
                    fallbackUri: forward:/fallback/order-service
            - id: payment-service
              uri: http://payment-service:8082
              predicates:
                - Path=/api/v1/payments/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: paymentServiceCircuitBreaker
                    fallbackUri: forward:/fallback/payment-service

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
    instances:
      orderServiceCircuitBreaker:
        baseConfig: default
      paymentServiceCircuitBreaker:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s

management:
  endpoints:
    web:
      exposure:
        include: health

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
